export default {
  creator: '@MehdiMstv',
  download: 'دانلود',
  getAnalytics: 'بزن بریم',
  github: 'GitHub',
  hashtag: 'اسنپ_من',
  heatmapTitle: 'محل‌های تردد',
  kmH: 'کیلومتر بر ساعت',
  loadData: 'در حال آماده‌سازی...',
  loginToSnapp: 'ورود به اسنپ',
  price: 'هزینه',
  saveChart: 'دریافت نمودار',
  saveData: 'ذخیره‌ی اطلاعات',
  snapp: 'Snapp',
  snappLoginHint: 'برای دریافت گزارش باید وارد حساب اسنپت بشی!',
  somethingWentWrong: 'خب کرش کردیم ^__^',
  total: 'مجموع',
  tweet: 'توییت',
  twitter: 'به اشتراک‌گذاری در توییتر',
  waitToComplete: 'تا رسیدن به مقصد منتظر بمون...',
  weArrived: 'رسیدیم...',
};
